package boundary;


import java.awt.Color;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        jpLogo = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        homeIcon = new javax.swing.JLabel();
        jlHome = new javax.swing.JLabel();
        btnProgramme = new javax.swing.JPanel();
        programmeIcon = new javax.swing.JLabel();
        jlProgramme = new javax.swing.JLabel();
        btnCourse = new javax.swing.JPanel();
        courseIcon = new javax.swing.JLabel();
        jlCourse = new javax.swing.JLabel();
        btnTutorialGroup = new javax.swing.JPanel();
        tutorialGroupIcon = new javax.swing.JLabel();
        jlTutorialGroup = new javax.swing.JLabel();
        btnStudent = new javax.swing.JPanel();
        studentIcon = new javax.swing.JLabel();
        jlStudent = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        titleHome = new javax.swing.JLabel();
        jbtCourse = new javax.swing.JButton();
        jbtProgramme = new javax.swing.JButton();
        jbtTutorialGroup = new javax.swing.JButton();
        jbtStudent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1263, 788));
        setMinimumSize(new java.awt.Dimension(1263, 788));
        setPreferredSize(new java.awt.Dimension(1263, 788));
        setResizable(false);

        bg.setBackground(new java.awt.Color(230, 230, 230));

        sidebar.setBackground(new java.awt.Color(203, 206, 210));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpLogo.setBackground(new java.awt.Color(203, 206, 210));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tarumt-logo.png"))); // NOI18N
        logo.setIconTextGap(0);
        logo.setMinimumSize(new java.awt.Dimension(1471, 414));

        javax.swing.GroupLayout jpLogoLayout = new javax.swing.GroupLayout(jpLogo);
        jpLogo.setLayout(jpLogoLayout);
        jpLogoLayout.setHorizontalGroup(
            jpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogoLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpLogoLayout.setVerticalGroup(
            jpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogoLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidebar.add(jpLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnHome.setBackground(new java.awt.Color(163, 167, 172));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N

        jlHome.setBackground(new java.awt.Color(130, 130, 130));
        jlHome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlHome.setText("Home");

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(homeIcon)
                .addGap(18, 18, 18)
                .addComponent(jlHome)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(homeIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        sidebar.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 266, -1));

        btnProgramme.setBackground(new java.awt.Color(172, 178, 187));
        btnProgramme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProgrammeMouseClicked(evt);
            }
        });

        programmeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/learning.png"))); // NOI18N

        jlProgramme.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlProgramme.setText("Programme");

        javax.swing.GroupLayout btnProgrammeLayout = new javax.swing.GroupLayout(btnProgramme);
        btnProgramme.setLayout(btnProgrammeLayout);
        btnProgrammeLayout.setHorizontalGroup(
            btnProgrammeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProgrammeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(programmeIcon)
                .addGap(18, 18, 18)
                .addComponent(jlProgramme)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        btnProgrammeLayout.setVerticalGroup(
            btnProgrammeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProgrammeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(btnProgrammeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(programmeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlProgramme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        sidebar.add(btnProgramme, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 266, -1));

        btnCourse.setBackground(new java.awt.Color(172, 178, 187));
        btnCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCourseMouseClicked(evt);
            }
        });

        courseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/books-stack-of-three.png"))); // NOI18N

        jlCourse.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlCourse.setText("Course");

        javax.swing.GroupLayout btnCourseLayout = new javax.swing.GroupLayout(btnCourse);
        btnCourse.setLayout(btnCourseLayout);
        btnCourseLayout.setHorizontalGroup(
            btnCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCourseLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(courseIcon)
                .addGap(18, 18, 18)
                .addComponent(jlCourse)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        btnCourseLayout.setVerticalGroup(
            btnCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCourseLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(btnCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(courseIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlCourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        sidebar.add(btnCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 266, -1));

        btnTutorialGroup.setBackground(new java.awt.Color(172, 178, 187));
        btnTutorialGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTutorialGroupMouseClicked(evt);
            }
        });

        tutorialGroupIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/multiple-users-silhouette.png"))); // NOI18N

        jlTutorialGroup.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlTutorialGroup.setText("Tutorial Group");

        javax.swing.GroupLayout btnTutorialGroupLayout = new javax.swing.GroupLayout(btnTutorialGroup);
        btnTutorialGroup.setLayout(btnTutorialGroupLayout);
        btnTutorialGroupLayout.setHorizontalGroup(
            btnTutorialGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTutorialGroupLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tutorialGroupIcon)
                .addGap(18, 18, 18)
                .addComponent(jlTutorialGroup)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        btnTutorialGroupLayout.setVerticalGroup(
            btnTutorialGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTutorialGroupLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(btnTutorialGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tutorialGroupIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlTutorialGroup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        sidebar.add(btnTutorialGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 266, -1));

        btnStudent.setBackground(new java.awt.Color(172, 178, 187));
        btnStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStudentMouseClicked(evt);
            }
        });

        studentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reading-book.png"))); // NOI18N

        jlStudent.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlStudent.setText("Student");

        javax.swing.GroupLayout btnStudentLayout = new javax.swing.GroupLayout(btnStudent);
        btnStudent.setLayout(btnStudentLayout);
        btnStudentLayout.setHorizontalGroup(
            btnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnStudentLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(studentIcon)
                .addGap(18, 18, 18)
                .addComponent(jlStudent)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        btnStudentLayout.setVerticalGroup(
            btnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnStudentLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(btnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(studentIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlStudent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        sidebar.add(btnStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 266, -1));

        footer.setBackground(new java.awt.Color(163, 167, 172));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(163, 167, 172));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleHome.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        titleHome.setForeground(new java.awt.Color(255, 255, 255));
        titleHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleHome.setText("Student Management System");
        header.add(titleHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 950, 67));

        jbtCourse.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jbtCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/books-stack-of-three.png"))); // NOI18N
        jbtCourse.setText("Manage Course");
        jbtCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCourseMouseClicked(evt);
            }
        });

        jbtProgramme.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jbtProgramme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/learning.png"))); // NOI18N
        jbtProgramme.setText("Manage Programme");

        jbtTutorialGroup.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jbtTutorialGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/multiple-users-silhouette.png"))); // NOI18N
        jbtTutorialGroup.setText("Manage Tutorial Group");

        jbtStudent.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jbtStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reading-book.png"))); // NOI18N
        jbtStudent.setText("Manage Student");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbtProgramme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtTutorialGroup, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE))
                                .addGap(0, 0, 0)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(0, 0, 0))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtProgramme, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtTutorialGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        setColor(btnHome);
        resetColor(btnProgramme);
        resetColor(btnCourse);
        resetColor(btnTutorialGroup);
        resetColor(btnStudent);       
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnProgrammeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProgrammeMouseClicked
        // TODO add your handling code here:
        resetColor(btnHome);
        setColor(btnProgramme);
        resetColor(btnCourse);
        resetColor(btnTutorialGroup);
        resetColor(btnStudent);
    }//GEN-LAST:event_btnProgrammeMouseClicked

    private void btnCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseMouseClicked
        // TODO add your handling code here:
        new CourseManage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCourseMouseClicked

    private void btnTutorialGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTutorialGroupMouseClicked
        // TODO add your handling code here:
        resetColor(btnHome);
        resetColor(btnProgramme);
        resetColor(btnCourse);
        setColor(btnTutorialGroup);
        resetColor(btnStudent);
    }//GEN-LAST:event_btnTutorialGroupMouseClicked

    private void btnStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentMouseClicked
        // TODO add your handling code here:
        resetColor(btnHome);
        resetColor(btnProgramme);
        resetColor(btnCourse);
        resetColor(btnTutorialGroup);
        setColor(btnStudent);
    }//GEN-LAST:event_btnStudentMouseClicked

    void setColor(JPanel panel) {
        panel.setBackground(new Color(163,167,172));
    }
    
    void resetColor(JPanel panel) {
        panel.setBackground(new Color(172,178,187));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home test = new Home();
                test.setVisible(true);
                test.bg.requestFocusInWindow();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnCourse;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnProgramme;
    private javax.swing.JPanel btnStudent;
    private javax.swing.JPanel btnTutorialGroup;
    private javax.swing.JLabel courseIcon;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JButton jbtCourse;
    private javax.swing.JButton jbtProgramme;
    private javax.swing.JButton jbtStudent;
    private javax.swing.JButton jbtTutorialGroup;
    private javax.swing.JLabel jlCourse;
    private javax.swing.JLabel jlHome;
    private javax.swing.JLabel jlProgramme;
    private javax.swing.JLabel jlStudent;
    private javax.swing.JLabel jlTutorialGroup;
    private javax.swing.JPanel jpLogo;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel programmeIcon;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel studentIcon;
    private javax.swing.JLabel titleHome;
    private javax.swing.JLabel tutorialGroupIcon;
    // End of variables declaration//GEN-END:variables
}
