/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary;

import java.awt.Color;

/**
 *
 * @author User
 */
public class TutorialGroupSearch extends javax.swing.JFrame {

    /**
     * Creates new form TutorialGroupSearch
     */
    public TutorialGroupSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        jpLogo = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        homeIcon = new javax.swing.JLabel();
        jlHome = new javax.swing.JLabel();
        btnProgramme = new javax.swing.JPanel();
        programmeIcon = new javax.swing.JLabel();
        jlProgramme = new javax.swing.JLabel();
        btnCourse = new javax.swing.JPanel();
        courseIcon = new javax.swing.JLabel();
        jlCourse = new javax.swing.JLabel();
        btnTutorialGroup = new javax.swing.JPanel();
        tutorialGroupIcon = new javax.swing.JLabel();
        jlTutorialGroup = new javax.swing.JLabel();
        btnStudent = new javax.swing.JPanel();
        studentIcon = new javax.swing.JLabel();
        jlStudent = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        searchBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchText = new javax.swing.JTextField();
        searchBtnPanel = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        footer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1263, 800));
        setMinimumSize(new java.awt.Dimension(1263, 800));
        setPreferredSize(new java.awt.Dimension(1263, 800));

        bg.setBackground(new java.awt.Color(230, 230, 230));

        sidebar.setBackground(new java.awt.Color(203, 206, 210));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpLogo.setBackground(new java.awt.Color(203, 206, 210));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tarumt-logo.png"))); // NOI18N
        logo.setIconTextGap(0);
        logo.setMinimumSize(new java.awt.Dimension(1471, 414));

        javax.swing.GroupLayout jpLogoLayout = new javax.swing.GroupLayout(jpLogo);
        jpLogo.setLayout(jpLogoLayout);
        jpLogoLayout.setHorizontalGroup(
            jpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogoLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpLogoLayout.setVerticalGroup(
            jpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogoLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidebar.add(jpLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnHome.setBackground(new java.awt.Color(172, 178, 187));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N

        jlHome.setBackground(new java.awt.Color(130, 130, 130));
        jlHome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlHome.setText("Home");

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(homeIcon)
                .addGap(18, 18, 18)
                .addComponent(jlHome)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(homeIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        sidebar.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 266, -1));

        btnProgramme.setBackground(new java.awt.Color(172, 178, 187));
        btnProgramme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProgrammeMouseClicked(evt);
            }
        });

        programmeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/learning.png"))); // NOI18N

        jlProgramme.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlProgramme.setText("Programme");

        javax.swing.GroupLayout btnProgrammeLayout = new javax.swing.GroupLayout(btnProgramme);
        btnProgramme.setLayout(btnProgrammeLayout);
        btnProgrammeLayout.setHorizontalGroup(
            btnProgrammeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProgrammeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(programmeIcon)
                .addGap(18, 18, 18)
                .addComponent(jlProgramme)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        btnProgrammeLayout.setVerticalGroup(
            btnProgrammeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProgrammeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(btnProgrammeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(programmeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlProgramme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        sidebar.add(btnProgramme, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 266, -1));

        btnCourse.setBackground(new java.awt.Color(172, 178, 187));
        btnCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCourseMouseClicked(evt);
            }
        });

        courseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/books-stack-of-three.png"))); // NOI18N

        jlCourse.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlCourse.setText("Course");

        javax.swing.GroupLayout btnCourseLayout = new javax.swing.GroupLayout(btnCourse);
        btnCourse.setLayout(btnCourseLayout);
        btnCourseLayout.setHorizontalGroup(
            btnCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCourseLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(courseIcon)
                .addGap(18, 18, 18)
                .addComponent(jlCourse)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        btnCourseLayout.setVerticalGroup(
            btnCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCourseLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(btnCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(courseIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlCourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        sidebar.add(btnCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 266, -1));

        btnTutorialGroup.setBackground(new java.awt.Color(163, 167, 172));
        btnTutorialGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTutorialGroupMouseClicked(evt);
            }
        });

        tutorialGroupIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/multiple-users-silhouette.png"))); // NOI18N

        jlTutorialGroup.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlTutorialGroup.setText("Tutorial Group");

        javax.swing.GroupLayout btnTutorialGroupLayout = new javax.swing.GroupLayout(btnTutorialGroup);
        btnTutorialGroup.setLayout(btnTutorialGroupLayout);
        btnTutorialGroupLayout.setHorizontalGroup(
            btnTutorialGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTutorialGroupLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tutorialGroupIcon)
                .addGap(18, 18, 18)
                .addComponent(jlTutorialGroup)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        btnTutorialGroupLayout.setVerticalGroup(
            btnTutorialGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTutorialGroupLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(btnTutorialGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tutorialGroupIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlTutorialGroup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        sidebar.add(btnTutorialGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 266, -1));

        btnStudent.setBackground(new java.awt.Color(172, 178, 187));
        btnStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStudentMouseClicked(evt);
            }
        });

        studentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reading-book.png"))); // NOI18N

        jlStudent.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlStudent.setText("Student");

        javax.swing.GroupLayout btnStudentLayout = new javax.swing.GroupLayout(btnStudent);
        btnStudent.setLayout(btnStudentLayout);
        btnStudentLayout.setHorizontalGroup(
            btnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnStudentLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(studentIcon)
                .addGap(18, 18, 18)
                .addComponent(jlStudent)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        btnStudentLayout.setVerticalGroup(
            btnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnStudentLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(btnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(studentIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlStudent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        sidebar.add(btnStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 266, -1));

        header.setBackground(new java.awt.Color(163, 167, 172));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Search Tutorial Group");
        header.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 67));

        searchBar.setBackground(new Color(242,242,242));
        searchBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N

        searchText.setBackground(new java.awt.Color(242, 242, 242));
        searchText.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        searchText.setForeground(new java.awt.Color(204, 204, 204));
        searchText.setText("Search");
        searchText.setBorder(null);
        searchText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTextFocusLost(evt);
            }
        });
        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchBarLayout = new javax.swing.GroupLayout(searchBar);
        searchBar.setLayout(searchBarLayout);
        searchBarLayout.setHorizontalGroup(
            searchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchBarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(searchText, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
        );
        searchBarLayout.setVerticalGroup(
            searchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(searchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(searchText)))
        );

        header.add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        searchBtnPanel.setBackground(new java.awt.Color(163, 167, 172));

        searchButton.setBackground(new java.awt.Color(153, 153, 153));
        searchButton.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.setBorderPainted(false);

        javax.swing.GroupLayout searchBtnPanelLayout = new javax.swing.GroupLayout(searchBtnPanel);
        searchBtnPanel.setLayout(searchBtnPanelLayout);
        searchBtnPanelLayout.setHorizontalGroup(
            searchBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchBtnPanelLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(searchButton))
        );
        searchBtnPanelLayout.setVerticalGroup(
            searchBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        header.add(searchBtnPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add Tutorial Group", "Search Tutorial Group", "Update Tutorial Group", "Delete Tutorial Group" }));
        jComboBox1.setSelectedIndex(1);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        header.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 192, 30));

        footer.setBackground(new java.awt.Color(163, 167, 172));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnProgrammeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProgrammeMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new ProgrammeManage().setVisible(true);
    }//GEN-LAST:event_btnProgrammeMouseClicked

    private void btnCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new CourseManage().setVisible(true);
    }//GEN-LAST:event_btnCourseMouseClicked

    private void btnTutorialGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTutorialGroupMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new TutorialGroupManage().setVisible(true);
    }//GEN-LAST:event_btnTutorialGroupMouseClicked

    private void btnStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new StudentManage().setVisible(true);
    }//GEN-LAST:event_btnStudentMouseClicked

    private void searchTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFocusGained
        if (searchText.getForeground().equals(new Color(204,204,204))) {
            searchText.setText("");
        }
        searchText.setForeground(Color.BLACK);
    }//GEN-LAST:event_searchTextFocusGained

    private void searchTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFocusLost
        if (searchText.getText().equals("")) {
            searchText.setText("Search");
            searchText.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_searchTextFocusLost

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (evt.getItem().equals("Add Tutorial Group")) {
            this.dispose();
            new TutorialGroupAdd().setVisible(true);
        } else if (evt.getItem().equals("Search Tutorial Group")) {

        } else if (evt.getItem().equals("Update Tutorial Group")) {
            this.dispose();
            new TutorialGroupUpdate().setVisible(true);
        } else if (evt.getItem().equals("Delete Tutorial Group")) {
            this.dispose();
            new TutorialGroupDelete().setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TutorialGroupSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TutorialGroupSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TutorialGroupSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TutorialGroupSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TutorialGroupSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnCourse;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnProgramme;
    private javax.swing.JPanel btnStudent;
    private javax.swing.JPanel btnTutorialGroup;
    private javax.swing.JLabel courseIcon;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlCourse;
    private javax.swing.JLabel jlHome;
    private javax.swing.JLabel jlProgramme;
    private javax.swing.JLabel jlStudent;
    private javax.swing.JLabel jlTutorialGroup;
    private javax.swing.JPanel jpLogo;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel programmeIcon;
    private javax.swing.JPanel searchBar;
    private javax.swing.JPanel searchBtnPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchText;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel studentIcon;
    private javax.swing.JLabel title;
    private javax.swing.JLabel tutorialGroupIcon;
    // End of variables declaration//GEN-END:variables
}
